create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  text text not null,
  complete boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy "Allow public read access on todos"
  on public.todos
  for select
  using (true);

create policy "Allow public insert access on todos"
  on public.todos
  for insert
  with check (true);

create policy "Allow public update access on todos"
  on public.todos
  for update
  using (true);

create policy "Allow public delete access on todos"
  on public.todos
  for delete
  using (true);
