-- Assign todos to calendar days
alter table public.todos
  add column if not exists day_date date;

update public.todos
set day_date = created_at::date
where day_date is null;

alter table public.todos
  alter column day_date set default (current_date);

alter table public.todos
  alter column day_date set not null;

create table if not exists public.day_reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day_date date not null,
  reflection text not null default '',
  closed_at timestamptz not null default now(),
  unique (user_id, day_date)
);

alter table public.day_reflections enable row level security;

drop policy if exists "Users can read own day reflections" on public.day_reflections;
drop policy if exists "Users can insert own day reflections" on public.day_reflections;
drop policy if exists "Users can update own day reflections" on public.day_reflections;
drop policy if exists "Users can delete own day reflections" on public.day_reflections;

create policy "Users can read own day reflections"
  on public.day_reflections for select
  using (auth.uid() = user_id);

create policy "Users can insert own day reflections"
  on public.day_reflections for insert
  with check (auth.uid() = user_id);

create policy "Users can update own day reflections"
  on public.day_reflections for update
  using (auth.uid() = user_id);

create policy "Users can delete own day reflections"
  on public.day_reflections for delete
  using (auth.uid() = user_id);
