create table if not exists public.user_categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.user_categories enable row level security;

drop policy if exists "Users can read own categories" on public.user_categories;
drop policy if exists "Users can insert own categories" on public.user_categories;
drop policy if exists "Users can update own categories" on public.user_categories;
drop policy if exists "Users can delete own categories" on public.user_categories;

create policy "Users can read own categories"
  on public.user_categories for select
  using (auth.uid() = user_id);

create policy "Users can insert own categories"
  on public.user_categories for insert
  with check (auth.uid() = user_id);

create policy "Users can update own categories"
  on public.user_categories for update
  using (auth.uid() = user_id);

create policy "Users can delete own categories"
  on public.user_categories for delete
  using (auth.uid() = user_id);
